config/routes.rb
Rails.application.routes.draw do
  resources :alunos
  get 'home/index'
  get 'aluno/index'

  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/aluno.rb
class Aluno < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/aluno_controller.rb
class AlunoController < ApplicationController 
    def index
        @alunos = Aluno.all
    end
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: %i[ show edit update destroy ]

  # GET /alunos or /alunos.json
  def index
    @alunos = Aluno.all
  end

  # GET /alunos/1 or /alunos/1.json
  def show
  end

  # GET /alunos/new
  def new
    @aluno = Aluno.new
  end

  # GET /alunos/1/edit
  def edit
  end

  # POST /alunos or /alunos.json
  def create
    @aluno = Aluno.new(aluno_params)

    respond_to do |format|
      if @aluno.save
        format.html { redirect_to aluno_url(@aluno), notice: "Aluno was successfully created." }
        format.json { render :show, status: :created, location: @aluno }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunos/1 or /alunos/1.json
  def update
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to aluno_url(@aluno), notice: "Aluno was successfully updated." }
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1 or /alunos/1.json
  def destroy
    @aluno.destroy

    respond_to do |format|
      format.html { redirect_to alunos_url, notice: "Aluno was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      @aluno = Aluno.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def aluno_params
      params.require(:aluno).permit(:nome, :idade, :data_de_nascimento, :contato)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/aluno/index.html.erb
<h1>Centro Educacional Novo Eldorado<h1>

<% @alunos.each do |aluno| %>

    <div>
        <p>registro: <%= aluno.id %></p>
        <p>nome: <%= aluno.nome %></p>
        <p>idade: <%= aluno.idade %></p>
        <p>data de nascimento: <%= aluno.data_de_nascimento %></p>
        <p>contato: <%= aluno.contato %></p>
    </div>

    <% end %>

app/views/alunos/_aluno.html.erb
<div id="<%= dom_id aluno %>">
  <p>
    <strong>Nome:</strong>
    <%= aluno.nome %>
  </p>

  <p>
    <strong>Idade:</strong>
    <%= aluno.idade %>
  </p>

  <p>
    <strong>Data de nascimento:</strong>
    <%= aluno.data_de_nascimento %>
  </p>

  <p>
    <strong>Contato:</strong>
    <%= aluno.contato %>
  </p>

</div>

app/views/alunos/_form.html.erb
<%= form_with(model: aluno) do |form| %>
  <% if aluno.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(aluno.errors.count, "error") %> prohibited this aluno from being saved:</h2>

      <ul>
        <% aluno.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :idade, style: "display: block" %>
    <%= form.number_field :idade %>
  </div>

  <div>
    <%= form.label :data_de_nascimento, style: "display: block" %>
    <%= form.date_field :data_de_nascimento %>
  </div>

  <div>
    <%= form.label :contato, style: "display: block" %>
    <%= form.number_field :contato %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/alunos/edit.html.erb
<h1>Editing aluno</h1>

<%= render "form", aluno: @aluno %>

<br>

<div>
  <%= link_to "Show this aluno", @aluno %> |
  <%= link_to "Back to alunos", alunos_path %>
</div>

app/views/alunos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Alunos</h1>

<div id="alunos">
  <% @alunos.each do |aluno| %>
    <%= render aluno %>
    <p>
      <%= link_to "Show this aluno", aluno %>
    </p>
  <% end %>
</div>

<%= link_to "New aluno", new_aluno_path %>

app/views/alunos/new.html.erb
<h1>New aluno</h1>

<%= render "form", aluno: @aluno %>

<br>

<div>
  <%= link_to "Back to alunos", alunos_path %>
</div>

app/views/alunos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @aluno %>

<div>
  <%= link_to "Edit this aluno", edit_aluno_path(@aluno) %> |
  <%= link_to "Back to alunos", alunos_path %>

  <%= button_to "Destroy this aluno", @aluno, method: :delete %>
</div>

app/views/home/index.html.erb
<h1> Oi <h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myproject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>